# Core 5.3 constructor declarations contain immutable generated metadata in the image heap.
Args = --initialize-at-build-time=io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanConstructorRef,io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanPropertyMemberRef,io.micronaut.validation.validator.metadata.AnnotationMember
