To use the Micronaut’s validation capabilities you must have the validation dependency on your classpath:

dependency:micronaut-validation-processor[scope="annotationProcessor",groupId="io.micronaut.validation"]

dependency:micronaut-validation[groupId="io.micronaut.validation"]

You can validate types, fields and parameters by applying `jakarta.validation` annotations to arguments. The `jakarta.validation-api` library exposes those annotations, but it unnecessary to specify it as a direct dependency. It is included transitively when using `micronaut-validation`.

NOTE: For Kotlin, add the `micronaut-validation-processor` dependency in https://docs.micronaut.io/4.4.3/guide/#kaptOrKsp[kapt or ksp scope], and for Groovy add `micronaut-validation-processor` in compileOnly scope.

== Supported Features

Note that Micronaut's implementation is not currently fully compliant with the https://beanvalidation.org/2.0/spec/[Bean Validator specification] as the specification heavily relies on reflection-based APIs.

The following features are unsupported at this time:

* Any interaction with the https://beanvalidation.org/2.0/spec/#constraintmetadata[constraint metadata API], since Micronaut uses compile-time generated metadata.
* XML-based configuration
* Instead of using `jakarta.validation.ConstraintValidator`, use api:validation.validator.constraints.ConstraintValidator[] (io.micronaut.validation.validator.constraints.ConstraintValidator) to define custom constraints, which supports validating annotations at compile time.

Micronaut's implementation includes the following benefits:

* Reflection and Runtime Proxy free validation, resulting in reduced memory consumption
* Smaller JAR size since Hibernate Validator adds another 1.4MB
* Faster startup since Hibernate Validator adds 200ms+ startup overhead
* Configurability via Annotation Metadata
* Support for Reactive Bean Validation
* Support for validating the source AST at compile time
* Automatic compatibility with GraalVM native without additional configuration

If you require full Bean Validator 2.0 compliance, add the `micronaut-hibernate-validator` module to your build, which replaces Micronaut's implementation.

dependency:micronaut-hibernate-validator[groupId="io.micronaut.beanvalidation"]

