plugins {
    id "io.micronaut.build.internal.validation-module"
}

dependencies {
    annotationProcessor mn.micronaut.inject.java

    api projects.micronautValidation
    compileOnly libs.jakarta.el.api

    testAnnotationProcessor mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.java.test
    testImplementation libs.jakarta.el.api
    testImplementation mnTest.micronaut.test.junit5
    testRuntimeOnly libs.jakarta.el.impl
    testRuntimeOnly mnTest.junit.jupiter.engine
}

micronautBuild {
    binaryCompatibility {
        enabledAfter("5.1.0")
    }
}
