plugins {
    id "io.micronaut.build.internal.validation-base"
    id "io.micronaut.build.internal.parent"
}

def jakartaTckCoverageReport = layout.projectDirectory.file('tests/jakarta-validation-tck/build/reports/jacoco/test/jacocoTestReport.xml')

plugins.withId('org.sonarqube') {
    sonar {
        properties {
            property 'sonar.coverage.jacoco.xmlReportPaths', [
                '**/build/reports/jacoco/test/jacocoTestReport.xml',
                jakartaTckCoverageReport.asFile.absolutePath
            ].join(',')
        }
    }
}
