pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M18'
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'validation-parent'

include 'validation'
include 'validation-bootstrap'
include 'validation-reflection'
include 'validation-xml'
include 'validation-el'
include 'validation-spec'
include 'validation-bom'
include 'validation-processor'
include 'test-suite'
include 'test-suite-groovy'
include 'test-suite-kotlin'

include 'tests:jakarta-validation-tck'

micronautBuild {
    useStandardizedProjectNames.set(true)
    importMicronautCatalog()
    importMicronautCatalog("micronaut-reactor")
    importMicronautCatalog("micronaut-rxjava3")
    importMicronautCatalog("micronaut-kotlin")
}
