plugins {
    id "io.micronaut.build.internal.validation-module"
    id "io.micronaut.build.internal.validation-generated-tests"
}

dependencies {
    api projects.micronautValidationBootstrap

    testAnnotationProcessor mn.micronaut.inject.java
    testImplementation mn.micronaut.inject.java.test
    testImplementation mnTest.micronaut.test.junit5
    testAnnotationProcessor projects.micronautValidationProcessor
    testRuntimeOnly projects.micronautValidationReflection
    testRuntimeOnly mnTest.junit.jupiter.engine
}

noReflection {
    // XML has no reflection permissions; enum names are parsed with explicit cases.
    forbidAll()
    severity "ERROR"
    forbid("javax.xml.parsers.DocumentBuilderFactory#newInstance")
}

micronautBuild {
    binaryCompatibility {
        enabledAfter("5.3.0")
    }
}
