plugins {
    id "io.micronaut.build.internal.validation-module"
}

dependencies {
    compileOnly mn.micronaut.core.processor
    compileOnly mn.micronaut.inject.java
    implementation projects.micronautValidation
    api libs.sourcegen.generator.bytecode
    api libs.sourcegen.annotations
    implementation libs.asm

    testImplementation mn.micronaut.core.reactive

    testImplementation mn.micronaut.http.client
    testImplementation mn.micronaut.inject.java.test
    testImplementation mn.micronaut.inject.groovy.test
}

