[versions]
managed-validation = "3.1.1"
jakarta-el-api = "6.0.1"
micronaut-el = "1.0.0-SNAPSHOT"
javafx = "21.0.6"

spotbugs = "4.9.8"
arquillian-container = "1.10.1.Final"
javax-annotation-api = "1.3.2"
jakarta-validation-tck = "3.1.1"
jakarta-cdi-api = "4.0.1"
jakarta-ejb-api = "4.0.1"

micronaut = "5.1.11"
micronaut-platform = "5.0.0-RC1"
micronaut-reactor = "4.0.0"
micronaut-rxjava3 = "4.0.0"
micronaut-kotlin = "5.0.0-RC1"

jmh = "1.37"

# gradle plugins
micronaut-gradle-plugin = "5.0.0-M1"

[libraries]
# core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }

# boms
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-rxjava3 = { module = 'io.micronaut.rxjava3:micronaut-rxjava3-bom', version.ref = "micronaut-rxjava3" }
micronaut-kotlin = { module = 'io.micronaut.kotlin:micronaut-kotlin-bom', version.ref = "micronaut-kotlin" }

# testing

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
kotlin-kotest-junit5 = { module = "io.kotest:kotest-runner-junit5-jvm" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
groovy-json = { module = "org.apache.groovy:groovy-json" }
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
arquillian-container = { module = "org.jboss.arquillian.container:arquillian-container-test-spi", version.ref = "arquillian-container" }
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version.ref = "javax-annotation-api" }
jakarta-cdi-api = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "jakarta-cdi-api" }
jakarta-ejb-api = { module = "jakarta.ejb:jakarta.ejb-api", version.ref = "jakarta-ejb-api" }
javafx-base = { module = "org.openjfx:javafx-base", version.ref = "javafx" }

# managed dependencies

managed-validation = { module = "jakarta.validation:jakarta.validation-api", version.ref = "managed-validation" }
jakarta-el-api = { module = "jakarta.el:jakarta.el-api", version.ref = "jakarta-el-api" }
micronaut-el = { module = "io.micronaut.el:micronaut-expression-language", version.ref = "micronaut-el" }
micronaut-el-interpreter = { module = "io.micronaut.el:micronaut-expression-language-interpreter", version.ref = "micronaut-el" }
micronaut-el-processor = { module = "io.micronaut.el:micronaut-expression-language-processor", version.ref = "micronaut-el" }
jakarta-validation-tck-tests = { module = 'jakarta.validation:validation-tck-tests', version.ref = "jakarta-validation-tck" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

# gradle plugins
gradle-micronaut = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
